# Generated by Django 5.0.2 on 2024-11-25 10:56

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enroll1',
            name='courses',
            field=models.CharField(choices=[('4-12', 'courses age 4-12'), ('13-16', 'courses age 13-16'), ('17', 'courses age 17')], max_length=200),
        ),
        migrations.CreateModel(
            name='Zoo_Booking',
            fields=[
                ('zoo_booking_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('zoo_booking_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('zoo_booking_date_arrive', models.DateField()),
                ('zoo_booking_date_leave', models.DateField()),
                ('zoo_booking_adults', models.IntegerField(default=0)),
                ('zoo_booking_children', models.IntegerField(default=0)),
                ('zoo_booking_old_oap', models.IntegerField(default=0)),
                ('zoo_total_cost', models.FloatField(default=0)),
                ('zoo_points', models.IntegerField(default=0)),
                ('zoo_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
